config/routes.rb
Pipeline::Application.routes.draw do
  resources :practice_groups

  resources :fiscal_projections

  resources :funnel_stages

  resources :financials 
  
  resources :programs

  resources :clients
  
  resources :divisions

  resources :opportunity_types

 
  root :to => "fiscal_projections#index"

end

app/models/fiscal_projection.rb
class FiscalProjection < ActiveRecord::Base
  belongs_to :program
  validates_presence_of :program_id, :on => :create, :message => "can't be blank"
  validates_presence_of :year, :on => :create, :message => "can't be blank"
  validates_presence_of :month, :on => :create, :message => "can't be blank"
  validates_presence_of :amount, :on => :create, :message => "can't be blank"
  validates_numericality_of :amount, :on => :create, :message => "is not a number"
  validates_numericality_of :amount, :on => :update, :message => "is not a number"
  has_many :comments
  
  def self.find_current(programs)
    month = Date.today.month
    year = Date.today.year
    program_ids = programs.collect {|p| p.id}
    where(:program_id => program_ids).where("(fiscal_projections.month >= ? AND fiscal_projections.year = ?) OR (fiscal_projections.month < ? AND fiscal_projections.year = ?)", month, year, month, year+1)
  end
end

app/controllers/fiscal_projections_controller.rb
class FiscalProjectionsController < ApplicationController
  
  
  # GET /fiscal_projections
  # GET /fiscal_projections.json
  def index
    @funnel_stages = FunnelStage.all

    @all_programs = Program.order("name")
    
    @programs = Program.includes(:division => :client)
    
    @programs = @programs.where(:id => params[:program_id]) if params[:program_id].present?
    
    @programs = @programs.page(params[:page]).per(25)
    
    @fiscal_projections = FiscalProjection.find_current(@programs)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fiscal_projections }
    end
  end
  
  
  # GET /fiscal_projections/1
  # GET /fiscal_projections/1.json
  def show
    @fiscal_projection = FiscalProjection.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fiscal_projection }
    end
  end

  # GET /fiscal_projections/new
  # GET /fiscal_projections/new.json
  def new
    @fiscal_projection = FiscalProjection.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fiscal_projection }
    end
  end

  # GET /fiscal_projections/1/edit
  def edit
    @fiscal_projection = FiscalProjection.find(params[:id])
  end

  # POST /fiscal_projections
  # POST /fiscal_projections.json
  def create
    @fiscal_projection = FiscalProjection.new(params[:fiscal_projection])

    respond_to do |format|
      if @fiscal_projection.save
        format.html { redirect_to "/" }
        format.json { render json: @fiscal_projection, status: :created, location: @fiscal_projection }
      else
        format.html { render action: "new" }
        format.json { render json: @fiscal_projection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fiscal_projections/1
  # PUT /fiscal_projections/1.json
  def update
    @fiscal_projection = FiscalProjection.find(params[:id])

    respond_to do |format|
      if @fiscal_projection.update_attributes(params[:fiscal_projection])
        format.html { redirect_to @fiscal_projection, notice: 'Fiscal Projection was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @fiscal_projection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fiscal_projections/1
  # DELETE /fiscal_projections/1.json
  def destroy
    @fiscal_projection = FiscalProjection.find(params[:id])
    @fiscal_projection.destroy

    respond_to do |format|
      format.html { redirect_to fiscal_projections_url }
      format.json { head :ok }
    end
  end
end

app/helpers/fiscal_projections_helper.rb
module FiscalProjectionsHelper
  def sorted_month_indexes
    return @sorted_month_indexes unless @sorted_month_indexes.blank?
    
    @sorted_month_indexes = [].tap do |months|

      current_month.upto(12) {|i| months.push(i)}

      if months.size != 12
        n = 12 - months.size
        for i in 1..n do 
          months.push(i) 
        end
      end
    end
  end
  
  def current_year
    @current_year ||= Time.now.year
  end
 
  def current_month
    @current_month ||= Time.now.month
  end

  def months
    @months ||= ['january', 'february', 'march', 'april', 'may', 'june', 'july', 'august', 'september','october', 'november', 'december']
  end
  
  # def sorted_month_names
  #   @sorted_month_names ||= self.months.rotate(current_month-1)
  # end
  
  def get_fiscal_projection(month, year, program_id)
    @fiscal_projections.detect{|projection| projection.program_id==program_id && projection.month==month && projection.year==year} || FiscalProjection.new
  end
  
  def sorted_months
    @sorted_months ||= [].tap do |months|
      sorted_month_indexes.each do |month|
        months << { :id => month, :year  => month < current_month ? current_year + 1 : current_year}
      end
    end
  end
  
end

app/views/fiscal_projections/_form.html.erb
<%= form_for(@fiscal_projection) do |f| %>
  <% if @fiscal_projection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fiscal_projection.errors.count, "error") %> prohibited this division from being saved:</h2>

      <ul>
      <% @fiscal_projection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label "Program" %><br />
    <%= f.select :program_id, Program.order('id DESC').collect {|p| [p.name,p.id]} %>
  </div>
  
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fiscal_projections/edit.html.erb
<h1>Editing Fiscal Projection</h1>

<%= render 'form' %>
<%= render 'february' %>
<%= link_to 'Show', @fiscal_projection %> |
<%= link_to 'Back', fiscal_projections_path %>

app/views/fiscal_projections/index.html.erb
<h1 class='header'><%= link_to 'TECHNEKES PIPELINE', fiscal_projections_path %></h1>
<tr>
<div id="new_program_link"><%= link_to 'Create A New Program', new_program_path %></div>
<div id="edit_program_link"><%= link_to 'Edit a Program', 'programs#show' %></div></tr>
<%= paginate @programs %>
<table id="data">
  <thead>
    <tr>
      <th class="client">Client</th>
      <th class="division">Division</th>
      <th class="program"><%= collection_select(:program, :name, @all_programs, :id, :full_name, options={:prompt => "-Select a Program"}) %></th>
      <th class="funnel_stage">Funnel Stage</th>
      <th class="practice_group">Practice Group</th>
      <th>Opportunity Type</th>
      <% sorted_month_indexes.each do |d|%>
        <th><%= Time.utc(current_year, d).strftime('%b') %></th>
      <% end %>
    </tr>
  </thead>
  
  <tbody>
    <% @programs.each do |program| %>
      <tr>
        <td><%= program.division.client.name %></td>
        <td><%= program.division.name %></td>
        <td><%= program.name %></td>
        <td class="funnel_stage">
         <%= collection_select(:funnel_stage, :name, @funnel_stages, :id, :name, options ={:selected => program.funnel_stage.id}, "data-program-id" => program.id)%>
        </td>
        <td class="practice_group"><%= program.division.practice_group.name %></td>
        <td class="opportunity_type"><%= program.opportunity_type.name %></td>
        <% sorted_months.each do |month| %>
          <% fiscal_projection = get_fiscal_projection(month[:id], month[:year], program.id) %>
          <td><%= text_field_tag 'month', fiscal_projection.amount, 'data-year' => month[:year], 'data-month' => month[:id], 'data-id' => fiscal_projection.id || -1, 'data-program-id'  => program.id %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>  
</table>


<%= paginate @programs %>

app/views/fiscal_projections/new.html.erb
<h1>Create a New Fiscal Projection</h1>
<p>If you have just created a new Program, please select the Year for the Program</p>
<%= render 'form' %>

<%= link_to 'Back', fiscal_projections_path %>

app/views/fiscal_projections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Month:</b>
  <%= @fiscal_projection.january %>
</p>


<%= link_to 'Edit', edit_fiscal_projection_path(@fiscal_projection) %> |
<%= link_to 'Back', fiscal_projections_path %>