config/routes.rb
Pipeline::Application.routes.draw do
  resources :practice_groups

  resources :fiscal_projections

  resources :funnel_stages

  resources :financials 
  
  resources :programs

  resources :clients
  
  resources :divisions

  resources :opportunity_types

 
  root :to => "fiscal_projections#index"

end

app/models/program.rb
class Program < ActiveRecord::Base
  validates_uniqueness_of :name, :scope => :division_id
  validates_presence_of :division_id, :on => :create, :message => "Program must belong to a Division"
  validates_presence_of :opportunity_type_id, :on => :create, :message => "can't be blank"
  validates_presence_of :funnel_stage_id, :on => :create, :message => "can't be blank"
  belongs_to :division
  belongs_to :opportunity_type #current_opportunity_type
  belongs_to :funnel_stage #current_funnel_stage
  has_many :fiscal_projections
  
  def full_name
    "#{division.name}: #{name}"
  end
  
end
  

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  # GET /programs
  # GET /programs.json
  def index
    if params[:division_id].present?
      @programs = Program.where(:division_id => params[:division_id])
    else
      @programs = Program.all
    end
    @divisions = Division.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @programs }
    end
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
    @program = Program.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @program }
    end
  end

  # GET /programs/new
  # GET /programs/new.json
  def new
    @program = Program.new
     
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @program }
    end
  end
  
  

  # GET /programs/1/edit
  def edit
    @program = Program.find(params[:id])
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(params[:program])
    
    respond_to do |format|
      if @program.save
        format.html { redirect_to "/" }
        format.json { render json: @program, status: :created, location: @program }
      else
        format.html { render action: "new" }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /programs/1
  # PUT /programs/1.json
  def update
    @program = Program.find(params[:id])
    
     if params[:funnel_stage_id].present?
       @program.update_attributes("funnel_stage_id" =>params[:funnel_stage_id])
     else
       @program = Program.find(params[:id])
     end
    respond_to do |format|
      if @program.update_attributes(params[:program])
        format.html { redirect_to "/", notice: 'Program was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program = Program.find(params[:id])
    @program.destroy

    respond_to do |format|
      format.html { redirect_to programs_url }
      format.json { head :ok }
    end
  end
  
  private
  
  # def build_program
  #   p = Program.new
  #   p.financials.build(:month => "shoe")
  #   p
  # end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.erb
<%= form_for(@program) do |f| %>
  <% if @program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% @program.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 **IF NO DIVISION EXISTS FOR THE PROGRAM YOU ARE CREATING, PLEASE CREATE A NEW DIVISION <%= link_to 'HERE', new_division_path %>**
    <div class="field">
      <tr>
        <%= f.label "Division" %>
        <%= f.select :division_id, Division.order('id DESC').collect {|n| [n.name,n.id]} %>
        
      </tr>
    </div>

    <div class="field">
      <tr>
        <%= f.label "Program Name" %>
        <%= f.text_field :name %>
      </tr>   
    </div>
    
    <div class="field">
      <tr>
        <%= f.label "Funnel Stage" %>
        <%= f.select :funnel_stage_id, FunnelStage.all.collect{|f| [f.name,f.id]}, options={:prompt => "-Select a Funnel Stage"} %>
      </tr>   
    </div>
    
    <div class="field">
      <tr>
        <%= f.label "Opportunity Type" %>
        <%= f.select :opportunity_type_id, OpportunityType.all.collect{|o| [o.name,o.id]}, options={:prompt => "-Select an Opportunity Type"} %>
      </tr>   
    </div>


      <div class="actions">
        <%= f.submit %>
      </div>

<% end %>

app/views/programs/edit.html.erb
<h1>Editing program</h1>

<%= render 'form' %>


<%= link_to 'Back to Programs Page', programs_path %>
<%= link_to 'Homepage', fiscal_projections_path %>

app/views/programs/index.html.erb
<h1>LIST OF PROGRAMS</h1>

<table>
  <thead>
  <tr>
    <th>Division</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td><%= select(:division, :id, @divisions.collect {|d| [d.name,d.id]}, :prompt  => "Select a Division")%></td>
  </tr>
  <tr>
    <td id="program"><%= select(:program, :id, [], options={:prompt  => "Select a Program"}) %></td>
  </tr>
  </tbody>
</table>

<br />

<%= link_to 'Homepage', fiscal_projections_path %>

app/views/programs/new.html.erb
<h1>Create a New Program</h1>

<%= render 'form' %>

<%= link_to 'Back', fiscal_projections_path %>

app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @program.name %>
</p>




<%= link_to 'Homepage', fiscal_projections_path %>
<%= link_to 'EDIT ANOTHER PROGRAM', programs_path %>