config/routes.rb
Pipeline::Application.routes.draw do
  resources :practice_groups

  resources :fiscal_projections

  resources :funnel_stages

  resources :financials 
  
  resources :programs

  resources :clients
  
  resources :divisions

  resources :opportunity_types

 
  root :to => "fiscal_projections#index"

end

app/models/division.rb
class Division < ActiveRecord::Base
  validates_uniqueness_of :name, :scope => :client_id
  validates_presence_of :name, :on => :create, :message => "can't be blank"
  validates_presence_of :practice_group_id, :on => :create, :message => "can't be blank"
  validates_presence_of :client_id, :on => :create, :message => "can't be blank"
  belongs_to :client
  has_many :programs
  belongs_to :practice_group

end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
 respond_to :json
  # GET /divisions
  # GET /divisions.json
  def index
   
    if params[:client_id].present?
      @divisions = Division.where(:client_id => params[:client_id])
    else
      @divisions = Division.all
    end
    
   

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @divisions }
      format.js { render :json => @divisions }
    end
  end

  # GET /divisions/1
  # GET /divisions/1.json
  def show
    @division = Division.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @division }
    end
  end

  # GET /divisions/new
  # GET /divisions/new.json
  def new
    @division = Division.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @division }
    end
  end

  # GET /divisions/1/edit
  def edit
    @division = Division.find(params[:id])
  end

  # POST /divisions
  # POST /divisions.json
  def create
    @division = Division.new(params[:division])

    respond_to do |format|
      if @division.save
        format.html { redirect_to new_program_path }
        format.json { render json: @division, status: :created, location: @division }
      else
        format.html { render action: "new" }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /divisions/1
  # PUT /divisions/1.json
  def update
    @division = Division.find(params[:id])

    respond_to do |format|
      if @division.update_attributes(params[:division])
        format.html { redirect_to @division, notice: 'Division was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /divisions/1
  # DELETE /divisions/1.json
  def destroy
    @division = Division.find(params[:id])
    @division.destroy

    respond_to do |format|
      format.html { redirect_to divisions_url }
      format.json { head :ok }
    end
  end
end

app/helpers/divisions_helper.rb
module DivisionsHelper
  
  
  
end

app/views/divisions/_form.html.erb
<%= form_for(@division) do |f| %>
  <% if @division.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@division.errors.count, "error") %> prohibited this division from being saved:</h2>

      <ul>
      <% @division.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label "Client" %><br />
    <%= f.select :client_id, Client.order('id DESC').collect {|n| [n.name,n.id]} %>
    **If no CLIENT exists for the Division you wish to create please click <%= link_to 'here', new_client_path %>**
  </div>
  
  
  <div class="field">
    <%= f.label 'Practice Group' %><br />
    <%= f.select :practice_group_id, PracticeGroup.order('name').collect {|p| [p.name,p.id]}, options={:prompt => "-Select a Practice Group"} %>
  </div>

  <div class="field">
    Division
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/divisions/edit.html.erb
<h1>Editing division</h1>

<%= render 'form' %>

<%= link_to 'Show', @division %> |
<%= link_to 'Back', divisions_path %>

app/views/divisions/index.html.erb
<h1>Listing divisions</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <tr>
    <% a = @divisions.collect{|n| n.name} %>
    <% a.each do |b| %>
      <%= b %><br />  
    <% end %>
   
  </tr>
</table>


<%= link_to 'New Division', new_division_path %>

app/views/divisions/new.html.erb
<h1>CREATE A NEW DIVISION</h1>

<%= render 'form' %>

<%= link_to 'Homepage', fiscal_projections_path %>

app/views/divisions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @division.name %>
</p>


<%= link_to 'Edit', edit_division_path(@division) %>
<%= link_to 'Back', divisions_path %>